// AUTO-GENERATED by tools/gen_voice.py — do not edit.
// Word times are the REAL ElevenLabs alignment; captions sync exactly.
import type { VoLine } from '../../lib/shorts';

export const VO: VoLine[] = [
  { text: 'Right now, gravity is pulling the Moon straight toward you.', start: 0.4, end: 4.07, words: [] },
  { text: 'It\'s been falling for four and a half billion years, and it still hasn\'t landed.', start: 5.1, end: 9.58, words: [] },
  { text: 'Same trick that keeps satellites up: fall, and keep missing.', start: 11.53, end: 15.61, words: [] },
  { text: 'Just from three hundred eighty four thousand kilometers out — sixty Earths away.', start: 16.23, end: 21.19, words: [] },
  { text: 'Pause. Does gravity even reach that far?', start: 21.8, end: 24.68, words: [] },
  { text: 'It does. It just fades, the farther out you go.', start: 25.19, end: 28.07, words: [] },
  { text: 'Surface gravity: nine point eight meters per second, every second.', start: 29.89, end: 34.2, words: [] },
  { text: 'The station\'s still at eighty eight percent of that.', start: 34.59, end: 36.99, words: [] },
  { text: 'But out at the Moon? Just three hundredths of one percent.', start: 38.85, end: 42.21, words: [] },
  { text: 'The station falls four meters a second. The Moon falls about one millimeter.', start: 43.98, end: 49.26, words: [] },
  { text: 'Double the distance, gravity drops to a quarter — every time. That\'s the inverse square law.', start: 49.99, end: 55.99, words: [] },
  { text: 'So the Moon isn\'t tied down by anything. It\'s falling, forever, just slow enough to keep missing.', start: 56.42, end: 62.9, words: [] },
];
